###
GET http://localhost:5000/users

### register
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Arsy Madya Budianto",
    "email": "amb@gmail.com",
    "password": "12345",
    "confPassword": "12345"	
}

### login
POST http://localhost:5000/login
Content-Type: application/json

{
    // "email": "amb@gmail.com",
    // "password": "32143"
    "email": "amb@gmail.com",
    "password": "12345"
}

### login with access key
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsIm5hbWUiOiJNYWhkYSBadWxpYSIsImVtYWlsIjoibXpAZ21haWwuY29tIiwiaWF0IjoxNjg2ODE1NTAyLCJleHAiOjE2ODY4MTU1MTd9.SoQSAWfrgjSEaPRYixryQAi7vyPpllyMZZ8OiSYhPfc

### updating expired access key
GET http://localhost:5000/token

### log out and delete access key
DELETE http://localhost:5000/logout